language: cpp
os: linux
dist: focal
before_install:
  - sudo docker run --privileged linuxkit/binfmt:v0.6
  - sudo docker run --rm --privileged multiarch/qemu-user-static:register
services:
  - docker
compiler:
  - gcc
jobs:
  include:
  - name: "armhf raspbian stretch"
    env: DOCKERFILE=Dockerfile-armhf-raspbian-stretch
  - name: "armhf raspbian buster"
    env: DOCKERFILE=Dockerfile-armhf-raspbian-buster
script: docker build -f $DOCKERFILE --build-arg CLOUDSMITH_API_KEY=${CLOUDSMITH_API_KEY} .
